/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Preview_macrosIndexRouteImport } from './routes/preview_macros/index'
import { Route as How_it_worksIndexRouteImport } from './routes/how_it_works/index'
import { Route as CalculatorIndexRouteImport } from './routes/calculator/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Preview_macrosIndexRoute = Preview_macrosIndexRouteImport.update({
  id: '/preview_macros/',
  path: '/preview_macros/',
  getParentRoute: () => rootRouteImport,
} as any)
const How_it_worksIndexRoute = How_it_worksIndexRouteImport.update({
  id: '/how_it_works/',
  path: '/how_it_works/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIndexRoute = CalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/how_it_works/': typeof How_it_worksIndexRoute
  '/preview_macros/': typeof Preview_macrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorIndexRoute
  '/how_it_works': typeof How_it_worksIndexRoute
  '/preview_macros': typeof Preview_macrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/how_it_works/': typeof How_it_worksIndexRoute
  '/preview_macros/': typeof Preview_macrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calculator/' | '/how_it_works/' | '/preview_macros/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculator' | '/how_it_works' | '/preview_macros'
  id: '__root__' | '/' | '/calculator/' | '/how_it_works/' | '/preview_macros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorIndexRoute: typeof CalculatorIndexRoute
  How_it_worksIndexRoute: typeof How_it_worksIndexRoute
  Preview_macrosIndexRoute: typeof Preview_macrosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview_macros/': {
      id: '/preview_macros/'
      path: '/preview_macros'
      fullPath: '/preview_macros/'
      preLoaderRoute: typeof Preview_macrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how_it_works/': {
      id: '/how_it_works/'
      path: '/how_it_works'
      fullPath: '/how_it_works/'
      preLoaderRoute: typeof How_it_worksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/': {
      id: '/calculator/'
      path: '/calculator'
      fullPath: '/calculator/'
      preLoaderRoute: typeof CalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorIndexRoute: CalculatorIndexRoute,
  How_it_worksIndexRoute: How_it_worksIndexRoute,
  Preview_macrosIndexRoute: Preview_macrosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
